### ISSUE TITLE
Error running download_stocks_ohlcv.py (first time)

### ISSUE THREAD

**Issue by rbianco3** [namuan/trading-utils#1]
**Command Attempted:**

py download_stocks_ohlcv.py

**Error Encountered:**

FileNotFoundError: [Errno 2] No such file or directory: 'data/large-cap.csv'

**Solution:**

Needed to download the SP 500 list via command. I assume this is a one time thing & hope me mentioning this helps someone.

py download_sp500_companies.py

**Notes:**

I wouldn't call this a bug; however I didn't see anything in the documents and thought it would be worth mentioning. I am a complete Git / Github newbie (but seasoned developer) so not really sure if this is along the right lines of what an issue should be. Disregard if this is waste of time or I did something wrong.

**Comment by namuan** [comment]
Thanks for raising this issue. 

There are some instructions under [Relative Strength (not RSI) using Price Momentum Oscillator](https://github.com/namuan/trading-utils#relative-strength-not-rsi-using-price-momentum-oscillator) to download the file from BarChart.

As the file isn't necessary to fetch stocks data therefore I'm making it optional to run it. 

https://github.com/namuan/trading-utils/commit/1af5a12fa58c007f26842ae8677003d276edc03a

Please re-open if it is still an issue.
